//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR2_UchebnayaPractika.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public System.DateTime DateAdd { get; set; }
        public string Equipment { get; set; }
        public string Serial_Number { get; set; }
        public string Type_Of_Malfunction { get; set; }
        public string Description_Problem { get; set; }
        public string Number_Phone { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Final_Description { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public Nullable<System.DateTime> Rough_Date { get; set; }
        public Nullable<System.DateTime> Close_Date { get; set; }
        public string Total_Materials_List { get; set; }
    
        public virtual Priority Priority { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
